/*
 * generated by Xtext 2.10.0
 */
package edelta.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import edelta.ui.wizard.EdeltaProjectCreatorCustom

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class EdeltaUiModule extends AbstractEdeltaUiModule {

	override bindIProjectCreator() {
		EdeltaProjectCreatorCustom
	}

}
