/**
 * 
 */
package edelta.lib;

/**
 * Base class for code generated by the Edelta DSL
 * 
 * @author Lorenzo Bettini
 *
 */
public abstract class AbstractEdelta {

	/**
	 * Performs the actual execution of the transformation.
	 * 
	 * @throws Exception
	 */
	public void execute() throws Exception {
		
	}

}
