/**
 * 
 */
package edelta.lib;

import org.eclipse.xtext.xbase.lib.Extension;

/**
 * A concrete implementation of {@link AbstractEdelta} that does not perform any
 * specific operation, but it contains protected field of type
 * {@link EdeltaStandardLibrary}, whose methods can be used as extension methods
 * by the code generated by the DSL generator.
 * 
 * @author Lorenzo Bettini
 *
 */
public class EdeltaDefaultRuntime extends AbstractEdelta {

	/**
	 * This is protected since it provides transparent access to the
	 * {@link EdeltaStandardLibrary} to source code of the DSL.
	 */
	@Extension
	protected EdeltaStandardLibrary stdLib;

	public EdeltaDefaultRuntime() {
		super();
		stdLib = new EdeltaStandardLibrary(this);
	}

	/**
	 * @param other
	 */
	public EdeltaDefaultRuntime(AbstractEdelta other) {
		super(other);
		stdLib = new EdeltaStandardLibrary(this);
	}

	public EdeltaDefaultRuntime(EdeltaModelManager modelManager) {
		super(modelManager);
		stdLib = new EdeltaStandardLibrary(this);
	}

}
