/*
 * generated by Xtext 2.10.0
 */
package edelta


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EdeltaStandaloneSetup extends EdeltaStandaloneSetupGenerated {

	def static void doSetup() {
		new EdeltaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
