/**
 * generated by Xtext 2.10.0
 */
package edelta;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.xml.namespace.XMLNamespacePackage;

import com.google.inject.Injector;

import edelta.edelta.EdeltaPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension
 * registry.
 */
public class EdeltaStandaloneSetup extends EdeltaStandaloneSetupGenerated {
	public static void doSetup() {
		new EdeltaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

	@Override
	public void register(final Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.Edelta.edelta")) {
			EPackage.Registry.INSTANCE.put("http://www.Edelta.edelta", EdeltaPackage.eINSTANCE);
		}
		if (!EPackage.Registry.INSTANCE.containsKey(XMLNamespacePackage.eNS_URI)) {
			EPackage.Registry.INSTANCE.put(XMLNamespacePackage.eNS_URI, XMLNamespacePackage.eINSTANCE);
		}
		super.register(injector);
	}
}
