<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myecoreforvalidation" nsURI="http://www.eclipse.org/emf/2002/MyecoreForValidation"
    nsPrefix="myecoreforvalidation">
  <eClassifiers xsi:type="ecore:EClass" name="MyEClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MyEEnum">
    <eLiterals name="first"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="myOtherEClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
