/*
 * generated by Xtext 2.11.0
 */
package edelta.ide

import com.google.inject.Guice
import edelta.EdeltaRuntimeModule
import edelta.EdeltaStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class EdeltaIdeSetup extends EdeltaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new EdeltaRuntimeModule, new EdeltaIdeModule))
	}
	
}
