/*
 * generated by Xtext 2.10.0
 */
package edelta.tests

import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(EdeltaInjectorProvider)
class EdeltaParsingTest extends EdeltaAbstractTest {

	@Test
	def void testEmptyProgram() {
		val result = parse('''
		''')
		Assert.assertNotNull(result)
	}

	@Test
	def void testSingleMetamodel() {
		val result = parse('''
			metamodel "ecore"
		''')
		Assert.assertNotNull(result)
	}

	@Test
	def void testTwoMetamodels() {
		val result = parse('''
			metamodel "ecore"
			metamodel "type"
		''')
		Assert.assertNotNull(result)
	}

}
