/*
 * generated by Xtext 2.10.0
 */
package edelta.tests

import com.google.inject.Inject
import edelta.edelta.EdeltaEcoreCreateEClassExpression
import org.eclipse.emf.ecore.EAttribute
import org.eclipse.emf.ecore.EClass
import org.eclipse.emf.ecore.EDataType
import org.eclipse.emf.ecore.EEnum
import org.eclipse.emf.ecore.EEnumLiteral
import org.eclipse.emf.ecore.ENamedElement
import org.eclipse.emf.ecore.EPackage
import org.eclipse.emf.ecore.EReference
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.xbase.typesystem.IBatchTypeResolver
import org.junit.Test
import org.junit.runner.RunWith

import static extension org.junit.Assert.*

@RunWith(XtextRunner)
@InjectWith(EdeltaInjectorProviderCustom)
class EdeltaTypeComputerTest extends EdeltaAbstractTest {

	@Inject extension IBatchTypeResolver

	@Test
	def void testTypeOfReferenceToEPackage() {
		referenceToEPackage.assertType(EPackage)
	}

	@Test
	def void testTypeOfReferenceToEClass() {
		referenceToEClass.assertType(EClass)
	}

	@Test
	def void testTypeOfReferenceToEDataType() {
		referenceToEDataType.assertType(EDataType)
	}

	@Test
	def void testTypeOfReferenceToEEnum() {
		referenceToEEnum.assertType(EEnum)
	}

	@Test
	def void testTypeOfReferenceToEAttribute() {
		referenceToEAttribute.assertType(EAttribute)
	}

	@Test
	def void testTypeOfReferenceToEReference() {
		referenceToEReference.assertType(EReference)
	}

	@Test
	def void testTypeOfReferenceToEEnumLiteral() {
		referenceToEEnumLiteral.assertType(EEnumLiteral)
	}

	@Test
	def void testTypeOfReferenceToUnresolvedENamedElement() {
		"ecoreref(NonExistant)".assertType(ENamedElement)
	}

	@Test
	def void testTypeOfReferenceToNullNamedElement() {
		"ecoreref".assertPrimitiveVoid
	}

	@Test
	def void testTypeOfReferenceToNullNamedElement2() {
		"ecoreref()".assertPrimitiveVoid
	}

	@Test
	def void testTypeOfCreateEClassExpression() {
		"createEClass Test in foo".assertType(EClass)
	}

	@Test
	def void testTypeOfCreateEAttributeExpression() {
		"createEClass Test in foo {
			createEAttribute myAttribute
		}".assertTypeOfCreateEClassBody(EAttribute)
	}

	def private assertType(CharSequence input, Class<?> expected) {
		input.parseWithTestEcore.lastExpression => [
			expected.canonicalName.assertEquals(
				resolveTypes.getActualType(it).identifier
			)
		]
	}

	def private assertPrimitiveVoid(CharSequence input) {
		input.parseWithTestEcore.lastExpression => [
			"void".assertEquals(
				resolveTypes.getActualType(it).identifier
			)
		]
	}

	def private assertTypeOfCreateEClassBody(CharSequence input, Class<?> expected) {
		input.parseWithTestEcore.lastExpression => [
			expected.canonicalName.assertEquals(
				resolveTypes.getActualType(
					(it as EdeltaEcoreCreateEClassExpression).body.expressions.last
				).identifier
			)
		]
	}

}
