<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myecore" nsURI="http://www.eclipse.org/emf/2002/Myecore" nsPrefix="myecore">
  <eClassifiers xsi:type="ecore:EClass" name="MyEClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MyENum">
    <eLiterals name="FirstEnumLiteral"/>
    <eLiterals name="SecondEnumLiteral" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyOtherEClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="MyNewClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ANewAttribute" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANewDerivedEClass" abstract="true" eSuperTypes="#//MyEClass"/>
</ecore:EPackage>
