/*
 * generated by Xtext 2.10.0
 */
package edelta.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class EdeltaWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public EdeltaWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
