<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testecoreforusages4" nsURI="http://my.testecoreforusages4.org"
    nsPrefix="testecoreforusages4">
  <eClassifiers xsi:type="ecore:EClass" name="UsePersonAndWorkplace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceToPerson" eType="ecore:EClass TestEcoreForUsages1.ecore#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceToWorkPlace" eType="ecore:EClass TestEcoreForUsages2.ecore#//WorkPlace"/>
  </eClassifiers>
</ecore:EPackage>
