/*
 * generated by Xtext 2.22.0
 */
package edelta.ui.labeling;

import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class EdeltaDescriptionLabelProvider extends XbaseDescriptionLabelProvider {

}
