# This workflow will build deploy the p2 repository to GitHub Pages

name: Deploy p2

on:
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK
      uses: actions/setup-java@v4.6.0
      with:
        java-version: 21
        distribution: temurin
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2
          !**/*edelta*
        key: ${{ runner.os }}-p2-deploy-${{ hashFiles('**/*.target', '**/pom.xml') }}
        restore-keys: ${{ runner.os }}-p2-deploy-
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'lorenzo.bettini@users.noreply.github.com'
    - name: Deploy p2
      run: >
        ./mvnw -f edelta.parent/pom.xml
        clean deploy
        -Prelease-composite,release-ide
        -Dgithub-update-repo=https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/LorenzoBettini/edelta-releases
