# This workflow will build deploy the p2 repository to GitHub Pages

name: Deploy p2

on:
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 17
        distribution: temurin
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Test rsync update
      run: >
        rsync -avP -e ssh lbettini@frs.sourceforge.net:/home/frs/project/edelta/products ./test
    - name: Test rsync commit
      run: >
        rsync -avP -e ssh README.md lbettini@frs.sourceforge.net:/home/frs/project/edelta/products/