# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# TODO: key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }} when all due profiles are used

name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
          !**/*edelta*
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven and SonarCloud
      run: xvfb-run ./mvnw -f edelta.parent/pom.xml -U clean verify -Pjacoco,build-ide,test-ide,run-its sonar:sonar -Dsonar.organization=lorenzobettini-github -Dsonar.host.url=https://sonarcloud.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: runner.os == 'Linux'
    - name: Build with Maven
      run: ./mvnw -f edelta.parent/pom.xml -U clean verify -Pbuild-ide,test-ide,run-its
      if: runner.os == 'macOS'
    - name: Build with Maven
      run: mvnw.cmd -f edelta.parent/pom.xml -U clean verify -Pbuild-ide,test-ide,run-its
      if: runner.os == 'Windows'
