# This workflow will build a Java project with Maven and analyzes it with SonarCloud
# This always run (push and PR)

name: Java CI with Maven and SonarCloud

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
          !**/*edelta*
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven and SonarCloud
      run: >
        xvfb-run
        ./mvnw -f edelta.parent/pom.xml
        -U clean verify
        -Pjacoco,build-ide,test-ide,run-its
        sonar:sonar
        -Dsonar.organization=lorenzobettini-github
        -Dsonar.host.url=https://sonarcloud.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

