# This workflow will build a Java project with Maven and analyzes it with SonarCloud
# This always run (push and PR)

name: Java CI with Maven and SonarCloud

on:
  push:
  pull_request:

jobs:
  build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    runs-on: ubuntu-latest
# not required anymore, thanks to Guice 5
#    env:
#      MAVEN_OPTS: --add-opens java.base/java.lang=ALL-UNNAMED

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        java-version: 17
        distribution: temurin

    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
          !**/*edelta*
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target', '**/maven-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-m2-

    # execute sonar:sonar only for internal PRs
    - name: Set Maven Additional Goals
      run: |
        echo "SONARGOAL=sonar:sonar" >> $GITHUB_ENV
      if: ${{ env.SONAR_TOKEN }}

    - name: Build with Maven and SonarCloud
      run: >
        xvfb-run
        ./mvnw -f edelta.parent/pom.xml
        clean verify
        -Pjacoco,test-ide
        -Dsonar.organization=lorenzobettini-github
        -Dsonar.host.url=https://sonarcloud.io
        $SONARGOAL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
          !**/*edelta*
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target', '**/maven-wrapper.properties') }}

    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: test-results-${{ runner.os }}
        path: '**/*.tests/target/surefire-reports'
    - name: Archive UI Tests Screenshots
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: screenshots-${{ runner.os }}
        path: '**/*.tests/screenshots'
    - name: Archive Logs
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: logs-${{ runner.os }}
        path: '**/*.tests/target/**/*.log'

