# This workflow will build a Java project with Maven
# This runs only on PR

name: Java CI with Maven on Windows and Mac

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-latest', 'windows-latest']
      fail-fast: false
    runs-on: ${{ matrix.os }}
# not required anymore, thanks to Guice 5
#    env:
#      MAVEN_OPTS: --add-opens java.base/java.lang=ALL-UNNAMED

    steps:
    - uses: actions/checkout@v2.5.0
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 17
        distribution: temurin

    - name: Restore cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
          !**/*edelta*
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target', '**/maven-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build with Maven
      run: ./mvnw -f edelta.parent/pom.xml clean verify '-Ptest-ide'

    - name: Save cache
      uses: actions/cache/save@v3
      if: always()
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
          !**/*edelta*
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target', '**/maven-wrapper.properties') }}

    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: test-results-${{ runner.os }}
        path: '**/*.tests/target/surefire-reports'
    - name: Archive UI Tests Screenshots
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: screenshots-${{ runner.os }}
        path: '**/*.tests/screenshots'
    - name: Archive Logs
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: logs-${{ runner.os }}
        path: '**/*.tests/target/**/*.log'
