# This workflow will build a Java project with Maven
# This runs only on PR

name: Java CI with Maven on Windows and Mac

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
          !**/*edelta*
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: ./mvnw -f edelta.parent/pom.xml clean verify -Pbuild-ide,test-ide,run-its
      if: runner.os == 'macOS'
    - name: Build with Maven
      run: .\mvnw.cmd -f edelta.parent/pom.xml clean verify '-Pbuild-ide,test-ide,run-its'
      if: runner.os == 'Windows'
